config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  get 'events/index'

  mount ActionCable.server => '/cable'
  match  '/rentals/index' => 'rentals#index', via: [:get]
  match '/rentals/new' => 'rentals#new', via: [:get]
  match '/rentals/parse_locations' => 'rentals#parse_locations', via: [:post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  after_create_commit { EventBroadcastJob.perform_later self }
  validates :message, presence: true
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :rental
  validates :rental_id, presence: true
  validates :timestamp, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude
end

app/models/rental.rb
class Rental < ApplicationRecord
  has_many :positions
  has_attached_file :csv
  validates :name, presence: true
  validates :csv, presence: true
  validates_attachment_content_type :csv, content_type: ['text/plain', 'text/csv', 'application/vnd.ms-excel']
  after_create_commit :create_event

  def success(process_csv)
    Event.create message: "Your csv file #{self.csv.path} has been processed for the Rental #{self.id}, total distance: #{self.kilometers}"
  end

  def failure(process_csv)
    Event.create message: "Your csv file #{self.csv.path} couldn't be processed for the Rental #{self.id}"
  end

  def process_locations
    positions = self.positions
	total_distance = 0
	positions.each_with_index do |p, ctr|
	 next_element = positions[ctr + 1]
	 total_distance = total_distance +  p.distance_to(next_element) if next_element
	end
	self.kilometers = total_distance
	self.save
  end

  def process_csv
	options = {:col_sep => ";", :row_sep => "\cM\n"}
    n = SmarterCSV.process(File.open(self.csv.path), options) do |array|
	  Position.create(rental_id: self.id, timestamp: array.first.values.first, latitude: array.first.values.second, longitude: array.first.values.third)
    end
	self.process_locations
  end
  handle_asynchronously :process_csv, :priority => 0
  
  private

  def create_event
    Event.create message: "Your csv file is being processed"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.reverse
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  
  def index
    @rentals = Rental.all.reverse
  end

  def new
    @rental = Rental.new
  end
  
  def parse_locations
    @rental = Rental.new(rental_params)
	@rental.name = DateTime.now.to_s
	if @rental.save
	  @rental.process_csv()
	  redirect_to root_path
	end
  end
 
  private

  def rental_params
    params.require(:rental).permit(:csv)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rentals_controller_helper.rb
module RentalsControllerHelper
end

app/views/events/_event.html.erb
<div class="event">
  <%= event.created_at.to_formatted_s(:short) %>: <%= event.message %>
</div>

app/views/events/index.html.erb
<h1>Activity Log</h1>
<p>
<%= link_to 'Access previous generations results', rentals_index_path if Rental.count > 0%>
<%= link_to 'Add a new csv file', rentals_new_path %>
<p>
 <div id="events">
   <%= render @events %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KooliTest</title>
    <%= csrf_meta_tags %>
	<%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/index.html.erb
<h1>Rentals index</h1>
<%= link_to 'Add a new csv file', rentals_new_path %>

<% @rentals.each do |r| %>
<p>
 <%= "Creation date: " %>
 <%= r.name %></br>
 <%= "CSV file: " %>
 <%= r.csv.path %></br>
 <%= "Number of locations: " %>
 <%= r.positions.count %></br>
 <%= "Total distance (kilometers): " %>
 <%= r.kilometers %></br>
</p>
<% end %>

app/views/rentals/new.html.erb
<h1>Please upload your positions CSV file</h1>

<%= form_for :rental, url: rentals_parse_locations_path, html: { multipart: true} do |f| %>
  <%= f.label :csv %>
  <%= f.file_field :csv %>
  <%= f.submit %>
<% end %>